# Generated by Django 6.0.7 on 2026-07-14 07:13

import apps.utils.helpers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Option',
                'verbose_name_plural': 'Product Options',
                'db_table': 'product_options',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productoption')),
            ],
            options={
                'verbose_name': 'Product Option Value',
                'verbose_name_plural': 'Product Option Values',
                'db_table': 'product_option_values',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('track_inventory', models.BooleanField(default=True)),
                ('allow_backorder', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('option1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants_option1', to='products.productoptionvalue')),
                ('option2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants_option2', to='products.productoptionvalue')),
                ('option3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants_option3', to='products.productoptionvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.utils.helpers.upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Image',
                'verbose_name_plural': 'Variant Images',
                'db_table': 'variant_images',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent'], name='product_cat_parent__fb81c8_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['title'], name='product_cat_title_c631b3_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['display_order'], name='product_cat_display_be2083_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_featured'], name='product_cat_is_feat_9321a9_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active'], name='product_cat_is_acti_f5a665_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['created_at'], name='product_cat_created_9c802d_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'title'), name='unique_category_per_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_brand_b2547a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='products_is_feat_19b203_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_created_e1ba5f_idx'),
        ),
        migrations.AddIndex(
            model_name='productoption',
            index=models.Index(fields=['product'], name='product_opt_product_50925b_idx'),
        ),
        migrations.AddIndex(
            model_name='productoption',
            index=models.Index(fields=['position'], name='product_opt_positio_bad5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='productoption',
            index=models.Index(fields=['is_active'], name='product_opt_is_acti_5271f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_product_option'),
        ),
        migrations.AddIndex(
            model_name='productoptionvalue',
            index=models.Index(fields=['option'], name='product_opt_option__65d766_idx'),
        ),
        migrations.AddIndex(
            model_name='productoptionvalue',
            index=models.Index(fields=['position'], name='product_opt_positio_abde86_idx'),
        ),
        migrations.AddIndex(
            model_name='productoptionvalue',
            index=models.Index(fields=['is_active'], name='product_opt_is_acti_65d9ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvalue',
            constraint=models.UniqueConstraint(fields=('option', 'value'), name='unique_option_value'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='product_var_product_017fde_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='product_var_sku_3a95f0_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price'], name='product_var_price_75df2c_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_default'], name='product_var_is_defa_3d8bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active'], name='product_var_is_acti_c7d489_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'option1', 'option2', 'option3'), name='unique_product_variant'),
        ),
        migrations.AddIndex(
            model_name='variantimage',
            index=models.Index(fields=['variant'], name='variant_ima_variant_018fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='variantimage',
            index=models.Index(fields=['position'], name='variant_ima_positio_bfe5ab_idx'),
        ),
        migrations.AddIndex(
            model_name='variantimage',
            index=models.Index(fields=['is_primary'], name='variant_ima_is_prim_a2f1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='variantimage',
            index=models.Index(fields=['is_active'], name='variant_ima_is_acti_289d70_idx'),
        ),
    ]
