# Generated by Django 6.0.7 on 2026-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='Check this to show product in New Arrivals section'),
        ),
    ]
