# Generated by Django 6.0.7 on 2026-07-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order of images (0 = first)'),
        ),
        migrations.AddIndex(
            model_name='variantimage',
            index=models.Index(fields=['sort_order'], name='variant_ima_sort_or_12d0f0_idx'),
        ),
    ]
