# Generated by Django 6.0.7 on 2026-07-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whatsapp_number', models.CharField(default='923248699647', help_text='WhatsApp number with country code (e.g., 923001234567)', max_length=20)),
                ('whatsapp_message_template', models.TextField(default="Hello! I'm interested in this product: {product_name}\nPrice: {price}\n\nCan you provide more details?", help_text='Message template for WhatsApp. Use {product_name}, {price}, {product_url} as variables.')),
                ('site_name', models.CharField(default='Hadi Sports', max_length=100)),
                ('site_email', models.EmailField(default='info@hadisports.com', max_length=254)),
                ('site_phone', models.CharField(default='+92 300 1234567', max_length=20)),
                ('site_address', models.TextField(default='297-C, P.I.A. Main Boulevard Road, Lahore, Pakistan')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
