# Generated by Django 6.0.7 on 2026-07-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatspp', '0002_alter_sitesetting_site_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_email',
            field=models.EmailField(default='info@hadisports.com', help_text='Email address for contact form submissions', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_phone',
            field=models.CharField(default='+92 300 1234567', help_text='Contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='whatsapp_number',
            field=models.CharField(default='923285774948', help_text='WhatsApp number with country code (e.g., 923285774948 for +92 328 5774948)', max_length=20),
        ),
    ]
