# Generated by Django 6.0.7 on 2026-07-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(db_index=True, help_text='Full name of the client', max_length=100)),
                ('client_profession', models.CharField(blank=True, help_text='Profession or designation of the client', max_length=100)),
                ('client_image', models.ImageField(blank=True, help_text='Client profile image (recommended size: 100x100)', null=True, upload_to='testimonials/')),
                ('testimonial_text', models.TextField(help_text='The testimonial/review text from the client')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Rating out of 5 stars')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = higher position')),
                ('is_featured', models.BooleanField(default=False, help_text='Check to feature this testimonial on homepage')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonials',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['display_order'], name='testimonial_display_77494d_idx'), models.Index(fields=['is_featured'], name='testimonial_is_feat_554925_idx'), models.Index(fields=['is_active'], name='testimonial_is_acti_eb2340_idx')],
            },
        ),
    ]
