# Generated by Django 6.0.7 on 2026-07-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Main heading for the banner', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or tagline', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description text')),
                ('image', models.ImageField(help_text='Banner image (recommended: 1920x800)', upload_to='hero_banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Mobile version of image (recommended: 768x600)', null=True, upload_to='hero_banners/mobile/')),
                ('button_text', models.CharField(blank=True, help_text='Button text (e.g., Shop Now)', max_length=50)),
                ('button_url', models.CharField(blank=True, help_text='Button link URL', max_length=200)),
                ('button_color', models.CharField(choices=[('primary', 'Green'), ('secondary', 'Orange'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('dark', 'Dark')], default='primary', help_text='Button color', max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = higher priority')),
                ('is_featured', models.BooleanField(default=False, help_text='Check to feature this banner')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'db_table': 'hero_banners',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['display_order'], name='hero_banner_display_42e8bc_idx'), models.Index(fields=['is_featured'], name='hero_banner_is_feat_993509_idx'), models.Index(fields=['is_active'], name='hero_banner_is_acti_e98a61_idx')],
            },
        ),
    ]
