# Generated by Django 6.0.7 on 2026-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_herobanner'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='herobanner',
            name='hero_banner_display_42e8bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='herobanner',
            name='hero_banner_is_feat_993509_idx',
        ),
        migrations.RemoveIndex(
            model_name='herobanner',
            name='hero_banner_is_acti_e98a61_idx',
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button_text',
            field=models.CharField(default='Shop Now', help_text='Button text', max_length=50),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button_url',
            field=models.CharField(blank=True, default='#', help_text='Button link URL', max_length=200),
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='mobile_image',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='subtitle',
        ),
    ]
