# Generated by Django 6.0.7 on 2026-08-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_herobanner_hero_banner_display_42e8bc_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herobanner",
            name="button_text",
        ),
        migrations.RemoveField(
            model_name="herobanner",
            name="button_url",
        ),
        migrations.RemoveField(
            model_name="herobanner",
            name="description",
        ),
        migrations.RemoveField(
            model_name="herobanner",
            name="title",
        ),
    ]
